language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - mvn clean package

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email:
    recipients:
      - daniel.wehrle@haufe-lexware.com      
    on_success: change
    on_failure: always # default: always
