/*
 * SonarQube FxCop Library
 * Copyright (C) 2014-2016 SonarSource SA
 * mailto:contact AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package org.sonar.plugins.fxcop;

import com.google.common.base.Charsets;
import com.google.common.collect.ImmutableList;
import com.google.common.io.Files;
import java.io.File;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import static org.assertj.core.api.Assertions.assertThat;

public class FxCopRulesetWriterTest {

  @Rule
  public TemporaryFolder tmp = new TemporaryFolder();

  @Test
  public void test() throws Exception {
    File file1 = tmp.newFile();
    new FxCopRulesetWriter().write(ImmutableList.of("foo", "bar"), file1);
    String contents1 = Files.toString(file1, Charsets.UTF_8);

    assertThat(contents1.replace("\r", "").replace("\n", "")).isEqualTo(
      "<?xml version=\"1.0\" encoding=\"utf-8\"?>" +
        "<RuleSet Name=\"SonarQube\" Description=\"Rule set generated by SonarQube\" ToolsVersion=\"12.0\">" +
        "  <Rules AnalyzerId=\"Microsoft.Analyzers.ManagedCodeAnalysis\" RuleNamespace=\"Microsoft.Rules.Managed\">" +
        "    <Rule Id=\"foo\" Action=\"Error\" />" +
        "    <Rule Id=\"bar\" Action=\"Error\" />" +
        "  </Rules>" +
        "</RuleSet>");

    File file2 = tmp.newFile();
    new FxCopRulesetWriter().write(ImmutableList.of("foo", "bar", "baz"), file2);
    String contents2 = Files.toString(file2, Charsets.UTF_8);
    assertThat(contents2)
      .contains("foo")
      .contains("bar")
      .contains("baz");
  }

}
